<?php
/** @var \Partner\Module\Block\Script $block */
?>
<script type="text/x-magento-init">
    {
        "*": {
            "Partner_Module/js/partner": {
                "url": "<?= /** @escapeNotVerified */ $block->getAjaxUrl() ?>",
                "partnerId": "<?= /** @escapeNotVerified */ $block->getPartnerId() ?>",
                "pacId": "<?= /** @escapeNotVerified */ $block->getPacId() ?>"
            }
        }
    }
</script>